source 'https://rubygems.org'
gem 'capybara'
gem 'thor'
gem 'selenium-webdriver'
gem 'rspec'
gem 'sqlite3'
gem 'telegram-bot-ruby'
gem 'pry'
gem 'jalalidate'
gem 'elasticsearch'
gem 'whenever'
gem 'google_url_shortener'

